services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - .:/var/www/html
    command: php artisan serve --host=0.0.0.0
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025